### ISSUE TITLE
Help Request 

### ISSUE THREAD

**Issue by bhandaribhumin** [bendyworks/cap-ml#12]
REPO : [msadal](https://www.npmjs.com/package/msadal-ios)
got error Argument labels '(call:, KClientID:, kGraphURI:, kAuthority:, redirectUri:)' do not match any available overloads

in file MSALiOS.swift 

line 32 ->XCODE ERROR  

 ADAuthentication(call: call, KClientID:String,kGraphURI: String,kAuthority: String,redirectUri: String).initADAL()

**Comment by vennelakodali** [comment]
could you provide the code that is causing the issue?

**Comment by bhandaribhumin** [comment]
@vennelakodali  Thanks a lot for quick response [GitRepo](https://github.com/bhandaribhumin/MSADALios)

**Comment by vennelakodali** [comment]
I did take a look at the repo, but didn't notice any **cap-ml** usage. So wondered if there's a code snippet I could look at. From the look of it though, it looks like an extraneous auth call that is failing, unrelated to cap-ml.

**Comment by bhandaribhumin** [comment]
yes but I follow same pattern which you use for create cap-ml but I got error "do not match any available overloads" did you know how I can fix and where I'm doing mistake. actually I'm not swift developer.

**Comment by vennelakodali** [comment]
aah I see, sure, I can take a look after work and see, although I'm not quite a swift dev either.

**Comment by bhandaribhumin** [comment]
ha ha... Thanks a lot @vennelakodali
